version = 0.1

[dev.deploy.parameters]
stack_name = "todo-serverless-fastapi-backend-dev"
s3_bucket = "todo-serverless-fastapi-sam-deployments-dev"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "Environment=\"dev\""

[stage.deploy.parameters]
stack_name = "todo-serverless-fastapi-backend-stage"
s3_bucket = "todo-serverless-fastapi-sam-deployments-stage"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "Environment=\"stage\""

[prod.deploy.parameters]
stack_name = "todo-serverless-fastapi-backend-prod"
s3_bucket = "todo-serverless-fastapi-sam-deployments-prod"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "Environment=\"prod\""
